const fs = require('fs');
let html = fs.readFileSync('index.html', 'utf8');

const newNav = '<nav class="navbar" id="navbar">\n        <div class="logo magnetic-btn">Mimo<span class="accent">!</span></div>\n        \n        <div class="nav-center" style="display: flex; align-items: center; gap: 1.5rem;">\n            <div class="search-container" id="searchContainer">\n                <button class="search-toggle magnetic-btn" id="searchToggle" aria-label="Buscar">\n                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg>\n                </button>\n                <div class="search-dropdown" id="searchDropdown">\n                    <input type="text" class="search-input" id="searchInput" placeholder="Buscar productos..." autocomplete="off">\n                    <div class="search-results" id="searchResults"></div>\n                </div>\n            </div>\n            <ul class="nav-links" id="navLinks">\n                <li><a href="#carousel" data-instant><span class="nav-text">Ofertas</span></a></li>\n                <li><a href="#products"><span class="nav-text">Productos</span></a></li>\n                <li><a href="#contact"><span class="nav-text">Contacto</span></a></li>\n            </ul>\n        </div>\n\n        <div class="nav-right">\n            <button class="cart-btn magnetic-btn" id="cartBtn" aria-label="Carrito">\n                <svg class="cart-icon-svg" xmlns="http://www.w3.org/2000/svg" width="46" height="46" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8">\n                    <path stroke-linecap="round" stroke-linejoin="round" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />\n                </svg>\n                <span class="cart-count" id="cartCount">0</span>\n            </button>\n            <button class="hamburger" id="hamburger" aria-label="Abrir menú">\n                <span class="bar"></span>\n                <span class="bar"></span>\n                <span class="bar"></span>\n            </button>\n        </div>\n    </nav>';

const regex = /<nav class="navbar" id="navbar">[\s\S]*?<\/nav>/;
if (regex.test(html)) {
    html = html.replace(regex, newNav);
    fs.writeFileSync('index.html', html, 'utf8');
    console.log('Fixed nav perfectly');
} else {
    console.log('Failed');
}
